### ISSUE TITLE
Feature Request: set a string value to NULL

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#108]
**Request:** Reset a field in the CSM Database back to NULL. (aka blank)

**Objective:** CSM update APIs should have the ability to set values to NULL in the CSM database. 

**Notes:**
- obviously not all CSM APIs should be able to set values in database to NULL
- only APIs with the tag of "update"?
- and even then, not all update APIs should let you set a value to NULL in the database.
- the important thing here is the feature, once the ability to implement the feature is abailable, then individual APIs can incorporate it, for specific attributes. 

**ToDo:**
- [x] test with a single API - node_attributes_update
- [x] test a single field - comment 
- [x] print the keyword on the back end logs (prove we got there)
- [x] update the database
- [x] pass a NULL value into a CSM API to set the value in the database to be NULL. 
- [x] support multiple fields on that API
- [x] support multiple APIs
- [x] improve re-usability of this new feature. 

**Feature branch associated with this issue:** https://github.com/NickyDaB/CAST/tree/feature-new/NULL_Database_fields_CSMAPIS

**Comment by fpizzano** [comment]
Adding Py to this issue @watson6282.

**Comment by NickyDaB** [comment]
as far as the `todo` item for `improve re-usability of this new feature.` we created a new issue for this, that will be worked on at a future release point.

**Comment by NickyDaB** [comment]
@watson6282 @fpizzano  this feature is now in the development branch and will be available as part of the next CSM release

**Comment by NickyDaB** [comment]
closing this issue.
