### ISSUE TITLE
request to ship API logging tools

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#310]
**Summary:**
request to ship API logging tools

**Is your feature request related to a problem? Please describe.**
@fpizzano  request that the logging tools that @etsai7 wrote be included in the next RPM ship.

**Describe the solution you'd like**
- please take the source files and build them into the RPM

**Additional context**
 - [x] please add in a feature to default log search location to the default install.
- [x] add feature to override that search location to a new directory should the user choose.
- [x] there seems to be a typo of "compute_stat" VS "computer_stat" please fix

**Issue Source:**
conversation with @fpizzano
