### ISSUE TITLE
CSM/UFM Inventory collection does not remove old records

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#336]
**Describe the bug**
When CSM runs its UFM inventory collection program, new records are recorded and old records are updated, but old records that are no longer reported via UFM restAPIs are not removed from CSM database.

**To Reproduce**
1. Go to: `/opt/ibm/csm/sbin`
2. Run: `standalone_ib_and_switch_collection`
3. look at records
4. pull power to a switch so that it is off and no longer reported via UFM restAPI inventory
5. Run: `standalone_ib_and_switch_collection` again.
6. you will see that the switch no longer shows up in the UFM output json, but is still in the CSM database

**Expected behavior**
Expect to see the record removed from CSM database live table. 

**Issue Source:**
@fpizzano  and I noticed this in the lab while running tests. 

**ToDo:**
- [x] remove old records from Switch inventory collection for CSM
- [x] remove old records from IB inventory collection
- [x] update the standalone program to have more feedback
- [x] ib improved feedback
- [x] switch improved feedback
- [x] switch module improved feedback
