### ISSUE TITLE
Jitter Mitigation (1.5.0)

### ISSUE THREAD

**Issue by mew2057** [IBM/CAST#453]
CSM 1.5.0 is to introduce a new Jitter Mitigation resolution scheme. Based on recommendations a core blinking strategy will be implemented to force processes off previously used/available cores.

The new features are broadly as follows:

- [x] Core Blinking.
   - [x] Blink only occupied cores to reduce start up
- [x] Jitter Reset.
    - Core isolation 0 reduces process clustering.
- [x] Configurable core isolation schema.
    - [x] Add Configuration options to core isolation patterns on the compute nodes.

**Comment by mew2057** [comment]
Moving to verify pending testing. PR has been made. I expect over the next month defects will be found in the implementation (due to the necessary refactor of the core selection code and the addition of SMT handling).

PR was made earlier in the dev cycle for integration with other components (as the interface is unlikely to change).
