### ISSUE TITLE
Big Data Store Ingestion Enhancements (1.6.0)

### ISSUE THREAD

**Issue by mew2057** [IBM/CAST#461]
Through real world testing and revised testing models several improvements must be made to the Big Data Ingestion pipeline:

- [ ] Timestamp resolution improvements.
   - [ ] CSM shipped timestamps should be automatically ingestible.
- [ ] A resolution strategy should be implemented for repairing bad index mappings.
- [ ] `csm-event-correlator` feature enhancements.
   - [ ] An *event history* should be added.
   - [ ] Send RAS should be able to directly interact with the CSM API.
   - [ ] Improved documentation and simplicity.
