### ISSUE TITLE
csm_bb_lv_delete upgrade 

### ISSUE THREAD

**Issue by NickyDaB** [IBM/CAST#541]
## Summary:
update bb lv delete - > num bytes read and bytes write to be optional as well. 

## ToDo:
- [x] update the comment on the struct to show that this parameter is optional. 
- [x] update cmd line interface to support optional params
- [x] update the daemon request handler to accept optional params. 
- [x] test that features work as expected

**Comment by NickyDaB** [comment]
has been merged into master. closing issue
